'use strict';

const path = require('path');
const { ROOT_DIR, SITE_URL } = require('../manifest');

const OUTPUT_PATH = path.join(ROOT_DIR, 'registry', 'generated', 'charts.ts');

function emitSiteData(items) {
  const charts = items.filter((item) => item.kind === 'chart');

  const entries = charts
    .map((chart) => [
      '  {',
      `    name: ${JSON.stringify(chart.name)},`,
      `    title: ${JSON.stringify(chart.title)},`,
      `    description: ${JSON.stringify(chart.description)},`,
      `    docsPath: ${JSON.stringify(`/docs/components/${chart.name}`)},`,
      `    registryUrl: ${JSON.stringify(`${SITE_URL}/r/${chart.name}.json`)},`,
      '  },',
    ].join('\n'))
    .join('\n');

  const content = [
    '// AUTO-GENERATED by registry/build.js — do not edit.',
    '// Source of truth: registry/manifest.js',
    '',
    'export interface RegistryChartSummary {',
    '  readonly name: string;',
    '  readonly title: string;',
    '  readonly description: string;',
    '  readonly docsPath: string;',
    '  readonly registryUrl: string;',
    '}',
    '',
    'export const REGISTRY_CHARTS: readonly RegistryChartSummary[] = [',
    entries,
    '];',
    '',
  ].join('\n');

  return [{ path: OUTPUT_PATH, content }];
}

module.exports = { emitSiteData, OUTPUT_PATH };
