import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";

import sharp from "sharp";

/** Dark to light. Index 0 is the darkest cell. */
const RAMP = " .:-=+*#%@";

const SOURCE = path.join(process.cwd(), "public/hero-portrait.jpg");
const OUTPUT = path.join(process.cwd(), "components/landing/hero/hero-ascii.ts");

const DEFAULT_COLUMNS = 120;
const DEFAULT_GAMMA = 1.5;

/** Monospaced cells are about twice as tall as they are wide. */
const CELL_ASPECT = 0.5;

/** How far the feather reaches in from the pasted image's edge, in pixels. */
const FEATHER = 48;

/**
 * Builds an alpha mask that fades the source image out at its own edges. The
 * source has a blurred backdrop that would otherwise meet the black canvas at a
 * hard rectangular seam, which converts into a visible box around the subject.
 */
function feather(width: number, height: number): Buffer {
  const mask = Buffer.alloc(width * height);

  for (let y = 0; y < height; y += 1) {
    for (let x = 0; x < width; x += 1) {
      const edge = Math.min(x, y, width - 1 - x, height - 1 - y);
      const t = Math.min(1, edge / FEATHER);
      // Smoothstep, so the falloff has no visible banding.
      mask[y * width + x] = Math.round(255 * t * t * (3 - 2 * t));
    }
  }

  return mask;
}

/**
 * Places the source on a 16:9 matte-black canvas, anchored right, so the left
 * of the field is empty for the headline.
 */
export async function compose(image: Buffer): Promise<Buffer> {
  const source = sharp(image);
  const { width = 0, height = 0 } = await source.metadata();

  const canvasHeight = height;
  const canvasWidth = Math.round((height * 16) / 9);
  const inset = Math.round(height * 0.06);

  const feathered = await source
    .ensureAlpha()
    .composite([
      {
        input: feather(width, height),
        raw: { width, height, channels: 1 },
        blend: "dest-in",
      },
    ])
    .png()
    .toBuffer();

  return sharp({
    create: {
      width: canvasWidth,
      height: canvasHeight,
      channels: 3,
      background: { r: 0, g: 0, b: 0 },
    },
  })
    .composite([
      { input: feathered, left: canvasWidth - width - inset, top: 0 },
    ])
    .png()
    .toBuffer();
}

export async function asciify(
  image: Buffer,
  options: { columns?: number; gamma?: number } = {},
): Promise<string> {
  const columns = options.columns ?? DEFAULT_COLUMNS;
  const gamma = options.gamma ?? DEFAULT_GAMMA;

  const composed = await compose(image);
  const { width = 0, height = 0 } = await sharp(composed).metadata();
  const rows = Math.max(1, Math.round((columns * height * CELL_ASPECT) / width));

  const { data } = await sharp(composed)
    .greyscale()
    .resize(columns, rows, { fit: "fill" })
    .raw()
    .toBuffer({ resolveWithObject: true });

  const lines: string[] = [];
  for (let y = 0; y < rows; y += 1) {
    let line = "";
    for (let x = 0; x < columns; x += 1) {
      const value = ((data[y * columns + x] ?? 0) / 255) ** gamma;
      line += RAMP[Math.min(RAMP.length - 1, Math.floor(value * RAMP.length))];
    }
    lines.push(line.replace(/\s+$/, ""));
  }

  return lines.join("\n");
}

async function main(): Promise<void> {
  const art = await asciify(await readFile(SOURCE), { columns: DEFAULT_COLUMNS });

  const moduleSource = `// Generated by scripts/ascii-portrait.ts from public/hero-portrait.jpg.
// Do not edit by hand — run \`npm run ascii:portrait\`.

export const HERO_ASCII_COLUMNS = ${DEFAULT_COLUMNS};

export const HERO_ASCII = ${JSON.stringify(art)};
`;

  await writeFile(OUTPUT, moduleSource, "utf8");
  process.stdout.write(`Wrote ${OUTPUT}\n`);
}

if (process.argv[1] && process.argv[1].includes("ascii-portrait")) {
  main().catch((error) => {
    process.stderr.write(String(error) + "\n");
    process.exitCode = 1;
  });
}
